version: 2

submodules:
  include: all

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .  
    - requirements: docs/requirements-doc.txt
    - method: pip
      path: .
